---
name: OpenGuides
version: 0.58
author: ~
abstract: ~
license: perl
requires:
  Algorithm::Diff: 0.13
  CGI: 2.92
  CGI::Carp: 0
  CGI::Cookie: 0
  Class::Accessor: 0
  Config::Tiny: 0
  DBD::Pg: 0
  Data::Dumper: 0
  File::Spec::Functions: 0
  File::Temp: 0
  Geography::NationalGrid: 0
  LWP::Simple: 0
  POSIX: 0
  Parse::RecDescent: 0
  Plucene: 0
  Template: 2.15
  Test::MockObject: 0.07
  Time::Piece: 0
  URI::Escape: 0
  Wiki::Toolkit: 0.73
  Wiki::Toolkit::Feed::Atom: 0
  Wiki::Toolkit::Feed::RSS: 0
  Wiki::Toolkit::Formatter::UseMod: 0
  Wiki::Toolkit::Plugin::Categoriser: 0
  Wiki::Toolkit::Plugin::Diff: 0
  Wiki::Toolkit::Plugin::Locator::Grid: 0
  Wiki::Toolkit::Plugin::RSS::Reader: 0
  XML::RSS: 0
recommends:
  DBD::SQLite: 0
  Geo::HelmertTransform: 0
  Test::HTML::Content: 0
  Wiki::Toolkit::Plugin::Ping: 0
build_requires:
  Module::Build: 0.18
dynamic_config: 1
provides:
  OpenGuides:
    file: lib/OpenGuides.pm
    version: 0.58
  OpenGuides::Build:
    file: lib/OpenGuides/Build.pm
  OpenGuides::CGI:
    file: lib/OpenGuides/CGI.pm
    version: 0.07
  OpenGuides::Config:
    file: lib/OpenGuides/Config.pm
  OpenGuides::Feed:
    file: lib/OpenGuides/Feed.pm
    version: 0.01
  OpenGuides::RDF:
    file: lib/OpenGuides/RDF.pm
    version: 0.09
  OpenGuides::Search:
    file: lib/OpenGuides/Search.pm
    version: 0.10
  OpenGuides::Template:
    file: lib/OpenGuides/Template.pm
    version: 0.12
  OpenGuides::Test:
    file: lib/OpenGuides/Test.pm
    version: 0.02
  OpenGuides::Utils:
    file: lib/OpenGuides/Utils.pm
    version: 0.09
generated_by: Module::Build version 0.26
