---
name: OpenGuides
version: 0.65
author: []
abstract: A complete web application for managing a collaboratively-written guide to a city or town.
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  Class::Accessor: 0
  Config::Tiny: 0
  Module::Build: 0.26
requires:
  Algorithm::Diff: 0.13
  CGI: 2.92
  CGI::Carp: 0
  CGI::Cookie: 0
  Class::Accessor: 0
  Config::Tiny: 0
  DBD::SQLite: 0
  Data::Dumper: 0
  Data::Validate::URI: 0
  File::Spec::Functions: 0
  File::Temp: 0
  Geo::Coordinates::UTM: 0
  Geography::NationalGrid: 0
  HTML::Entities: 0
  LWP::Simple: 0
  List::Util: 0
  MIME::Lite: 0
  Net::Netmask: 0
  POSIX: 0
  Parse::RecDescent: 0
  Plucene: 0
  Template: 2.15
  Time::Piece: 0
  URI::Escape: 0
  Wiki::Toolkit: 0.77
  Wiki::Toolkit::Feed::Atom: 0
  Wiki::Toolkit::Feed::RSS: 0
  Wiki::Toolkit::Formatter::UseMod: 0
  Wiki::Toolkit::Plugin::Categoriser: 0
  Wiki::Toolkit::Plugin::Diff: 0
  Wiki::Toolkit::Plugin::JSON: 0
  Wiki::Toolkit::Plugin::Locator::Grid: 0
  Wiki::Toolkit::Plugin::RSS::Reader: 0
  XML::RSS: 0
build_requires:
  Class::Accessor: 0
  Config::Tiny: 0
  Data::Dumper: 0
  Module::Build: 0.26
recommends:
  DBD::SQLite: 0
  Geo::HelmertTransform: 0
  Test::HTML::Content: 0
  Test::Pod: 0
  Wiki::Toolkit::Plugin::Ping: 0
dynamic_config: 1
provides:
  OpenGuides:
    file: lib/OpenGuides.pm
    version: 0.65
  OpenGuides::Build:
    file: lib/OpenGuides/Build.pm
    version: 0.02
  OpenGuides::CGI:
    file: lib/OpenGuides/CGI.pm
    version: 0.09
  OpenGuides::Config:
    file: lib/OpenGuides/Config.pm
    version: 0.06
  OpenGuides::Feed:
    file: lib/OpenGuides/Feed.pm
    version: 0.02
  OpenGuides::JSON:
    file: lib/OpenGuides/JSON.pm
    version: 0.02
  OpenGuides::RDF:
    file: lib/OpenGuides/RDF.pm
    version: 0.14
  OpenGuides::Search:
    file: lib/OpenGuides/Search.pm
    version: 0.13
  OpenGuides::Template:
    file: lib/OpenGuides/Template.pm
    version: 0.15
  OpenGuides::Test:
    file: lib/OpenGuides/Test.pm
    version: 0.06
  OpenGuides::Utils:
    file: lib/OpenGuides/Utils.pm
    version: 0.12
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
